<a href="https://colab.research.google.com/github/HunRajveer/Pandas/blob/main/Pandas_Class2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 2: DataFrame Basics
Welcome to **Class 2**. Today we’ll learn how to **inspect**, **select**, and **organize** data inside a DataFrame.

## 1 Inspecting Data
Quick ways to understand your dataset:
- `head(n)` → first *n* rows (default 5)
- `tail(n)` → last *n* rows
- `info()` → columns, non-null counts, and dtypes
- `shape` → (rows, columns)
- `dtypes` → data type of each column

In [2]:
import pandas as pd

# Create a small DataFrame
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)
print(b.head(3))# DEFAULT FIRST FIVE VALUE
# tail() this will return n rows
print(b.tail(2)) # same as head default 5 value from bottom
print(b.info()) # it will provide info like no of rows and col and datatype and null or notnull
print(b.shape)
print(b.dtypes) # dtypes will return data type of col

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
    Name  Age  Score
3  David   40     85
4   Emma   22     95
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Score   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes
None
(5, 3)
Name     object
Age       int64
Score     int64
dtype: object

## 2 Selecting Columns & Rows
Ways to access parts of a DataFrame:
- Single column → `df['col']`
- Multiple columns → `df[['col1','col2']]`
- Label-based selection → `df.loc[row_label, col_label]`
- Integer-index selection → `df.iloc[row_idx, col_idx]`
Tip: `:` means "all rows/columns" in that dimension.

In [4]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
# we will do slecting cols
df[['Name','Age']] # we need to pass a list inside list when we want to select multiple cols

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [6]:
# creating a new cols
df['experience']= ['12','10','31','9'] # make sure to enter data same langth

    Name  Age      City  Salary experience
0   John   28  New York   65000         12
1   Anna   34     Paris   70000         10
2  Peter   29    Berlin   62000         31
3  Linda   42    London   85000          9

    Name  Age      City  Salary experience
0   John   28  New York   65000         12
1   Anna   34     Paris   70000         10
2  Peter   29    Berlin   62000         31
3  Linda   42    London   85000          9

## 3 Index & Columns Overview
- `df.index` → row labels
- `df.columns` → column names
- `df.values` → underlying NumPy array (read-only; prefer using DataFrame ops)

In [11]:
# b.index it will tell from where our index start and stop
print(df.index) # output - RangeIndex(start=0, stop=4, step=1)
#b.columns it will gives the name of cols
print(df.columns) # output- Index(['Name', 'Age', 'City', 'Salary', 'experience'], dtype='object')


#df.values # output -array([['John', 28, 'New York', 65000, '12'],
      # ['Anna', 34, 'Paris', 70000, '10'],
      # ['Peter', 29, 'Berlin', 62000, '31'],
      # ['Linda', 42, 'London', 85000, '9']], dtype=object)
print(df.values) #our dataframe will convert into matrix form and display

array([['John', 28, 'New York', 65000, '12'],
       ['Anna', 34, 'Paris', 70000, '10'],
       ['Peter', 29, 'Berlin', 62000, '31'],
       ['Linda', 42, 'London', 85000, '9']], dtype=object)

## 4 Renaming Columns & Setting an Index
- Rename columns → `df.rename(columns={'old':'new'}, inplace=False)`
- Set a column as index → `df.set_index('column_name', inplace=False)`
- Reset index → `df.reset_index(inplace=False)`
 If you don't use `inplace=True`, remember to assign the result back to a variable.

In [18]:
# df.rename(columns={'old':'new'},inplace = ture) inplace will
# inplace will change original dataframe if its fales then no change else change
df.rename(columns={'Name':'Employee_Nme','Salary':'Income'},inplace = True)

# b.set_index('column_name', inplace=False) this will change the index


# we can reset also

In [19]:
df

  Employee_Nme  Age      City  Income experience
0         John   28  New York   65000         12
1         Anna   34     Paris   70000         10
2        Peter   29    Berlin   62000         31
3        Linda   42    London   85000          9

In [27]:
# selecting a rows
# .loc  is use to target a rows df.loc[1]
# another way of doing same df.iloc[2]
df.iloc[2]
# when we want to  select multiple rows then
df.loc[[1,2,3]]

  Employee_Nme  Age    City  Income experience
1         Anna   34   Paris   70000         10
2        Peter   29  Berlin   62000         31
3        Linda   42  London   85000          9

In [32]:
df
# when we want to do spacific slicing means first two row and 2 and 3 cols
df.iloc[[0,1,2,3]][['Employee_Nme','Income','experience']]

  Employee_Nme  Income experience
0         John   65000         12
1         Anna   70000         10
2        Peter   62000         31
3        Linda   85000          9

In [47]:
# condition like less then or greater then etc
df[(df['Income']>70000)&(df['experience']>'10')]

  Employee_Nme  Age    City  Income experience
3        Linda   42  London   85000          9

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Employee_Nme  4 non-null      object
 1   Age           4 non-null      int64
 2   City          4 non-null      object
 3   Income        4 non-null      int64
 4   experience    4 non-null      object
dtypes: int64(2), object(3)
memory usage: 292.0+ bytes

## 5 Basic Attributes Recap
- `df.columns` → names of all columns
- `df.index` → row labels
- `df.values` → NumPy array (data only)
These are handy for quick checks and loops (though vectorized ops are preferred).

## Mini Practice
1. Create a DataFrame with at least 5 rows and 4 columns (mix of numeric + text).
2. Show the first 3 rows, last 2 rows, and the info.
3. Select a sub-DataFrame with only 2 columns.
4. Rename one column and set any column as index, then reset it back.
5. Print `df.shape`, `df.dtypes`, and `df.columns`.

In [ ]:
import pandas as pd

# Create a DataFrame with at least 5 rows & 4 columns (mix of numbers + text)
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "City": ["Delhi", "Mumbai", "Pune", "Bangalore", "Chennai"],
    "Score": [85, 91, 78, 88, 95]
}

df = pd.DataFrame(data)

# Show the first 3 rows, last 2 rows, and info
# your code here

# Select a sub-DataFrame with only 2 columns
# your code here

# Rename one column and set any column as index, then reset it back
# your code here

# Print df.shape, df.dtypes, and df.columns
# your code here

---
## ✅ Summary
- You learned to **inspect** a DataFrame (`head`, `tail`, `info`, `shape`, `dtypes`).
- You practiced **selecting** columns/rows using `[]`, `.loc`, and `.iloc`.
- You explored **index/columns** and basic attributes.
- You **renamed** columns and **set/reset** an index.

Next up: **Data Cleaning Essentials** (missing values, types, duplicates).