<a href="https://colab.research.google.com/github/HunRajveer/Pandas/blob/main/Pandas_Class1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 1: Introduction & Setup
Welcome to your first class on **Pandas**. In this session, we'll learn what Pandas is, why we use it, and how to get started with Series and DataFrames.

## 1 What is Pandas and Why Use It?
Pandas is a powerful **Python library** for data analysis and manipulation.

Key points:
- Provides two main data structures: **Series** (1D) and **DataFrame** (2D).
- Makes working with tabular data easy and fast.
- Ideal for cleaning, transforming, and analyzing datasets.
- Works well with other libraries like NumPy, Matplotlib, and Scikit-Learn.

## 2 Installing & Importing Pandas
To install pandas, open your terminal or command prompt and run:
```bash
pip install pandas
```
Then, you can import it in Python as follows:

In [1]:
import pandas as pd # pandas name is come from panel data which is a economic term of representing multi-d data
"""
[] -> 1D array
[[],[],[],[]] #2d array , matrix
"""

'\n[] -> 1D array\n[[],[],[],[]] #2d array , matrix\n'

## 3 Understanding Series & DataFrame
- **Series**: One-dimensional labeled array, like a column in Excel.
- **DataFrame**: Two-dimensional table, similar to an Excel sheet or SQL table.

### Creating a Series from Python Lists or Dictionaries

In [ ]:
import pandas as pd # series is vertically stack and only have one col
marks = pd.Series([30,40,50,60,70],
                  index=['Ronaldo','Messi','Virat','Dhoni','Mbappe'])
print(marks)

Ronaldo    30
Messi      40
Virat      50
Dhoni      60
Mbappe     70
dtype: int64

### Creating a DataFrame

In [6]:
#Multiple columns -> DataFrame. # data frame is a collection on series which allign vertically with sae langth
# we can create a series using list or array or dict
import numpy as np

data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
cols = ["Name","Age","City","Salary"]
arr = np.array(data_list)
# we need to pass col name becasuse default
df = pd.DataFrame(arr,columns= cols)
df
# this is how we create a dataframe using vector

    Name Age      City Salary
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

### Creating DataFrame from NumPy Arrays

In [ ]:
information = pd.DataFrame([
  ['Rahul', 52, 80],
  ['Devraj', 22, 85],
  ['Abhishek',60,55]
], columns=['Name','Age','Marks'])

print(information)
print(information.loc[2])
print(information.loc[2, 'Marks'])

       Name  Age  Marks
0     Rahul   52     80
1    Devraj   22     85
2  Abhishek   60     55
55

In [ ]:
#Generate a 3X4 matrix with random numbers (1-13) using numpy
#name the columns as [A,B,C,D]

import numpy as np
import pandas as pd

arr = np.random.randint(1,100, size=(3,4))

arr_df = pd.DataFrame(arr, columns=['A','B','C','D'])
print(arr_df)

    A   B   C   D
0  84  27  83  38
1  89   5  85  25
2  77  17  62  50

In [8]:
# creating dataframe using dict
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

### Reading CSV / Excel Files (Sneak Peek)
You can read external data using:
```python
pd.read_csv('file.csv')
```
```python
pd.read_excel('file.xlsx')
```
We will explore this in detail later.

---
**Summary**
- Pandas is a must-know library for data analysis.
- We learned about Series & DataFrames.
- We saw how to create them from lists, dictionaries, NumPy arrays, and got a sneak peek at CSV/Excel files.