<a href="https://colab.research.google.com/github/HunRajveer/Pandas/blob/main/Pandas_class3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 3: Data Cleaning Essentials
Welcome to **Class 3** of our Pandas series. Today we’ll learn how to clean and prepare data for analysis.

## Handling Missing Values
Real-world datasets often have missing data. Pandas offers:
- `isna()` / `isnull()` → detect missing values (returns True/False)
- `dropna()` → remove missing values (rows/columns)
- `fillna()` → replace missing values with a given value or method (e.g., forward fill)

Always inspect how much data is missing before deciding to drop or fill.

In [4]:
import pandas as pd
import numpy as np
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
# isnull() or isna() detect missing values returns True
b = pd.DataFrame(data)
print(b.isna())
print(b.isna().sum())  # this will give count of null values row wise
print(b.dropna()) # it will remove entire row which causd lost in data
 # it will resolve the problem of dropna() method by keeping rows we need to passs value
# jo bhi int none  data type wala value ko mean sa replace kerta hai aur obj wali ko mode ya placeholder sa
# we can apply threshhold means drop a row only if it have at least X number of non-null value

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False
A    1
B    0
C    2
D    3
dtype: int64
     A  B    C    D
0  1.0  1  1.0  1.0

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [8]:
print(b)
b.dropna(thresh=4)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

     A  B    C    D
0  1.0  1  1.0  1.0

In [10]:
# if we wantto fill null value manually then we use fillna
b.fillna(0)
# or we can pass custome value by targating cols
new_value = {
    'A': 0,
    'B': 1,
    'C': 2,
    'D': 3
}
b.fillna(value=new_value)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  0.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

## Changing Data Types (`astype`)
- Convert a column to a different type using `astype()`.
- Examples: converting strings to numbers, integers to floats, or columns to category.

Be careful: make sure the data is compatible with the new type!

In [13]:
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

c = pd.DataFrame(a)
c['Age'].astype(float) # this will do type conversion
# obj or str cannot typecase into int

0    25.0
1    30.0
2    35.0
3    40.0
4    22.0
Name: Age, dtype: float64

## Replacing Values (`replace`)
- Use `replace()` to substitute specific values or patterns.
- Useful for cleaning labels, fixing typos, or mapping categories.

In [17]:
c['Name'].replace('Emma','deep').astype(str)
c['Age'].replace(35,99).astype(str)

0    25
1    30
2    99
3    40
4    22
Name: Age, dtype: object

## Dropping Rows & Columns (`drop`)
- `drop(labels, axis=0)` → drop rows by index labels.
- `drop(labels, axis=1)` → drop columns by name.
- Use `inplace=True` if you want to modify the DataFrame directly.

In [ ]:
 #axis = 0 remove row
 # for axis = 1 remove col
b.drop(index = 2,axis =1)

    Name  Age  Score
0  Alice   25     88
1    Bob   30     92
3  David   40     85
4   Emma   22     95

## Detecting & Removing Duplicates
- `duplicated()` → returns a Boolean Series marking duplicate rows.
- `drop_duplicates()` → remove duplicate rows.
- You can specify `subset` (columns) and `keep` ('first', 'last', or False).

In [ ]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "David"],
    "Age": [25, 30, 35, 25, 30, 25],
    "Score": [88, 92, 79, 88, 92, 85]
}

df = pd.DataFrame(data)
print(df.duplicated().sum()) # return number of duplicate
print(df.drop_duplicates(inplace = True)) # exect identical rows aati hai tho hee remove kerage

2
None

## Mini Practice
1. Create a messy DataFrame with missing values, wrong data types, typos, extra columns, and duplicates.
2. Clean it step-by-step using what you learned:
   - Handle missing values
   - Change data types
   - Replace incorrect values
   - Drop unnecessary rows/columns
   - Remove duplicates

In [23]:
import pandas as pd
import numpy as np

# 1. Create a messy DataFrame
data = {
    "Name": ["Alice", "Bob", "Chrlie", "David", "Alice", None],
    "Age": ["25", "30", None, "40", "25", "30"],      # ages stored as strings, with missing value
    "City": ["Delhi", "Mumbai", "Pun", "Bangalore", "Delhi", "Mumbai"],  # typo: "Pun" -> "Pune"
    "Score": [85, None, 78, 88, 85, 91],              # missing value in Score
    "Extra": ["x", "y", "z", "x", "y", "z"]           # extra column we don't really need
}

df = pd.DataFrame(data)

print("Original messy DataFrame:")
print(df)

# 2. Handle missing values
# Fill or drop as needed
new_value = {
    "Name": "Unknown",
    "Age": 0,
    "City": "Unknown",
    "Score": 0
}
df = df.fillna(value=new_value)

# 3. Change data types
# Convert Age to int, Score to float, etc.
df['Age'] = df['Age'].astype(int)
df['Score'] = df['Score'].astype(float)

# 4. Replace incorrect values
# Fix 'Pun' -> 'Pune', maybe unify Name spellings if needed
df['City'] = df['City'].replace('Pun', 'Pune')

# 5. Drop unnecessary rows/columns
# Remove 'Extra' or any row you don't want
df = df.drop(columns=['Extra'],inplace=True)
df

# 6. Remove duplicates
# Use duplicated() and drop_duplicates()

# 7. Final clean DataFrame
# Print the cleaned DataFrame and check info()

Original messy DataFrame:
     Name   Age       City  Score Extra
0   Alice    25      Delhi   85.0     x
1     Bob    30     Mumbai    NaN     y
2  Chrlie  None        Pun   78.0     z
3   David    40  Bangalore   88.0     x
4   Alice    25      Delhi   85.0     y
5    None    30     Mumbai   91.0     z

---
## Summary
- Learned to handle missing values (`isna`, `dropna`, `fillna`).
- Converted column data types with `astype`.
- Cleaned up incorrect entries with `replace`.
- Removed unwanted rows/columns with `drop`.
- Detected and removed duplicates.